#
# Copyright 2026 Peter Bestler <peter.bestler@liebherr.com>
#
# This software is supplied under the terms of the MIT License, a
# copy of which should be located in the distribution where this
# file was obtained (LICENSE.txt).  A copy of the license may also be
# found online at https://opensource.org/licenses/MIT.
#

bridges.mqtt.env-test {
	server = "mqtt-tcp://127.0.0.1:1883"
	clientid = "bridge-${NANOMQ_TEST_CLIENT_SUFFIX}-${VIN}"
	username = "${NANOMQ_TEST_USERNAME}"
	password = "secret-${NANOMQ_TEST_PASSWORD}"
}
